### ISSUE TITLE
Hugo with lazy loading and WebP + responsive images

### ISSUE THREAD

**Issue by verlanmar** [fundor333/fundor333-source#116]
Hi Fundor333!

If possible, would you please enhance your Hugo image render hook by adding responsive images feature, like here:

https://www.bennettnotes.com/notes/hugo-responsive-images-with-markdown-render-hook/

And thank you for your article!

https://fundor333.com/post/2021/hugo-with-lazy-loading-and-webp/

**Comment by fundor333** [comment]
Thanks. I am rewriting all the render hook and making a post about it. Tomorrow or the day after I post it
